### ISSUE TITLE
SJ25

### ISSUE THREAD

**Issue by limelowjack** [etransport/py9b#2]
Any chance you could locate/obtain tools for the SJ35?

**Comment by HelaFaye** [comment]
Although I hate Lime for firing me as a mechanic, the SJ is an entirely different beast whose motor controller and display are nothing like the Ninebot and Xiaomi. My only point being, that is out of scope for the perceived goal of this organization (reversing the Xiaomi and Ninebot electric scooter [which are incredibly similar]).

**Comment by flowswitch** [comment]
Doing a similar research on Lime looks quite problematic - no public tools to dump the communications/firmware updates, no legal ways to posess a such scooter.
